import { Metadata } from "next";
import Navigate from "../component/page";

export const metadata: Metadata = {
  title: {
    template: "%s | NextJs",
    default: "Loading",
  },
  description: "Generated by Next.js",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navigate></Navigate>
        {children}
      </body>
    </html>
  );
}
